micronaut:
  application:
    name: propostaGrpc

grpc:
  server:
    port: ${SERVER_PORT:50051}
    health:
      enable: true

datasources:
  default:
    url: ${DB_URI:`jdbc:postgresql://localhost:5432/keycloak`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:`keycloak`}
    password: ${DB_PASSWORD:`password`}
    schema-generate: CREATE_DROP
    dialect: POSTGRES


jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

analise:
  financeira:
    api: ${ANALISE_FINANCEIRA:`http://localhost:9999`}

cartoes:
  api: ${API_CARTOES:`http://localhost:8888`}

scheduler:
  delay: ${SCHEDULER_DELAY:`1m`}

endpoints:
  all:
    sensitive: false
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS